import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import { Toaster } from "sonner";

import "./globals.css";
import { AppNavbar } from "@/components/app-navbar";
import { AppPostHogProvider } from "@/components/providers/posthog-provider";
import { PostHogUserSync } from "@/components/providers/posthog-user-sync";
import { QueryProvider } from "@/components/providers/query-provider";
import { getSession } from "@/lib/auth/session";
import { cn } from "@/lib/utils";

const jetbrainsMono = JetBrains_Mono({ subsets: ["latin"], variable: "--font-mono" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const user = session
    ? { id: session.userId, email: session.email }
    : null;

  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-mono",
        jetbrainsMono.variable,
      )}
    >
      <body className="flex min-h-full flex-col">
        <AppPostHogProvider>
          <QueryProvider>
            <PostHogUserSync userId={user?.id ?? null} />
            <AppNavbar user={user} />
            <div className="flex min-h-0 flex-1 flex-col">{children}</div>
          </QueryProvider>
        </AppPostHogProvider>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
